version: "3"
services:
  frontend:
    container_name: next-app
    build: 
        context: .
        dockerfile: "./Dockerfile"
    env_file: "./.env"
    restart: always
    env_file: .env
  nginx:
    image: "nginx:stable-alpine"
    depends_on:
        - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf