version: "3"
services:
  frontend:
    image : "aarushgoyal/next-and-chakra:latest"
    build: 
        context: .
        dockerfile: "./Dockerfile"
    env_file: "./.env"
    restart: always
    deploy:
      replicas: 4
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    env_file: .env
  nginx:
    image: "nginx:stable-alpine"
    depends_on:
        - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf